# Generated by Django 3.2.8 on 2022-02-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardData',
        ),
    ]
